myriadsocial/myriad-api

src/enums/index.ts
src/enums/visibility-type.enum.ts
src/interceptors/pagination.interceptor.ts
src/migrations/1.0.0.migration.ts
src/models/index.ts
src/models/mention-user.model.ts
src/models/post.model.ts
src/services/experience.service.ts
src/services/friend.service.ts
src/services/tag.service.ts

- MYR-912: Add visibility field
- MYR-913: Add NSFW tag field
- MYR-915: Add mention field
- added new fields in Post Model
- improved query

Improved Post Collection

---

src/__tests__/integration/controllers/comment.controller.integration.ts
src/__tests__/integration/controllers/delete-collection.controller.integration.ts
src/__tests__/integration/controllers/friend.controller.integration.ts
src/__tests__/integration/controllers/report.controller.integration.ts
src/__tests__/unit/report.controller.unit.ts
src/controllers/deleted-collection.controller.ts
src/controllers/friend.controller.ts
src/controllers/report.controller.ts
src/controllers/user-currency.controller.ts
src/enums/notification-type.enum.ts
src/services/notification.service.ts

For example:
- Feature
- Bug
- Refactor …

Add function notification on change report status

---

src/interceptors/pagination.interceptor.ts

For example:
- Feature
- Bug
- Refactor …

Added new filter for search post

---

.github/workflows/alpha.yml
.github/workflows/beta.yml
.github/workflows/main.yml
.github/workflows/publish-draft-release-candidate.yml
.github/workflows/release-candidate.yml
.github/workflows/release.yml
LICENSE

Added gh workflow trigger by tag and added gh workflow for publish draft release candidate

ci: added gh workflow trigger by tag

---

src/interceptors/pagination.interceptor.ts

For example:
- Feature
- Bug
- Refactor …

fixed search post by query

---

src/interceptors/initial-creation.interceptor.ts
src/services/metric.service.ts

For example:
- Feature
- Bug
- Refactor …

fixed counting public metric

---

src/__tests__/integration/controllers/comment.controller.integration.ts
src/__tests__/integration/controllers/friend.controller.integration.ts
src/controllers/comment.controller.ts
src/interceptors/pagination.interceptor.ts
src/services/notification.service.ts

For example:
- Feature
- Bug
- Refactor …

Fixed mention notifications

---

src/__tests__/acceptance/comment.acceptance.ts
src/__tests__/integration/controllers/comment.controller.integration.ts
src/__tests__/integration/controllers/friend.controller.integration.ts
src/__tests__/integration/controllers/post.controller.integration.ts
src/__tests__/integration/controllers/transaction.controller.integration.ts
src/models/notification.model.ts
src/services/notification.service.ts

For example:
- Feature
- Bug
- Refactor …

Added new field in notification model

---

src/jobs/update-exchange-rate.job.ts

For example:
- Feature
- Bug
- Refactor …

fixed update exchange rate job

---

.github/workflows/alpha.yml
.github/workflows/beta.yml
.github/workflows/main.yml
.github/workflows/release-candidate.yml
.github/workflows/release.yml

Add new env variable & fix connect to k8s cluster

Add new env variable & fix connect to k8s cluster

---

src/__tests__/integration/controllers/transaction.controller.integration.ts
src/services/notification.service.ts

For example:
- Feature
- Bug
- Refactor …

fixed notifications referenceId for transaction

---

.maintain/docker/Dockerfile
src/application.ts
src/controllers/post.controller.ts
src/enums/platform-type.enum.ts
src/services/social-media.service.ts

- post.controlller.ts: /posts/import endpoint
- Added Telegram case
- src/services/social-media.service.ts
- new function: fetchTelegramMsgFromGun() which gets telegram message data from Gun.
- Unable to get the timestamp on the message in myriad-scraper because it doesn't show up in the GET response
- [x ] My changes generate no new warnings
- [ x] Any dependent changes have been merged and published in downstream modules
- [ x] Have you added yourself as the Assignee?
- [ x] Have you added 1 or more leads as the Reviewer?
- [ x] Have you chosen 1-2 of the following labels?
- Feature
- Bug
- Refactor
- Test
- Documentation

[MYR-1122] Import telegram individual telegram post

---

src/utils/url.utils.ts

For example:
- Feature
- Bug
- Refactor …

fixed regex

---

src/enums/visibility-type.enum.ts
src/services/friend.service.ts

For example:
- Feature
- Bug
- Refactor …

fixed visibility enum

---

package.json
src/__tests__/acceptance/account-setting.acceptance.ts
src/__tests__/acceptance/comment.acceptance.ts
src/__tests__/acceptance/notification-setting.acceptance.ts
src/__tests__/acceptance/user.acceptance.ts
src/__tests__/helpers/database.helper.ts
src/__tests__/helpers/given-instances.ts
src/__tests__/helpers/given-repositories.ts
src/__tests__/integration/controllers/comment.controller.integration.ts
src/__tests__/integration/controllers/friend.controller.integration.ts
src/__tests__/integration/controllers/post.controller.integration.ts
src/__tests__/integration/controllers/transaction.controller.integration.ts
src/controllers/index.ts
src/controllers/user-account-setting.controller.ts
src/controllers/user-notification-setting.controller.ts
src/enums/account-setting-type.enum.ts
src/enums/index.ts
src/interceptors/initial-creation.interceptor.ts
src/models/account-setting.model.ts
src/models/index.ts
src/models/notification-setting.model.ts
src/models/user.model.ts
src/repositories/account-setting.repository.ts
src/repositories/index.ts
src/repositories/notification-setting.repository.ts
src/repositories/user.repository.ts
src/services/notification.service.ts
src/services/social-media.service.ts
yarn.lock

For example:
- Feature
- Bug
- Refactor …

Save settings for notifications

---

src/__tests__/integration/controllers/comment.controller.integration.ts
src/__tests__/integration/controllers/friend.controller.integration.ts
src/__tests__/integration/controllers/post.controller.integration.ts
src/__tests__/integration/controllers/transaction.controller.integration.ts
src/__tests__/integration/controllers/user-social-media.controller.integration.ts
src/__tests__/unit/user-social-media.controller.unit.ts
src/controllers/deleted-collection.controller.ts
src/controllers/user-social-media.controller.ts
src/enums/notification-type.enum.ts
src/services/notification.service.ts

For example:
- Feature
- Bug
- Refactor …

Added more notifications item

---

src/models/currency.model.ts

For example:
- Feature
- Bug
- Refactor …

Added new field in currency model

---

src/__tests__/acceptance/post.acceptance.ts
src/config.ts
src/controllers/friend.controller.ts
src/interceptors/initial-creation.interceptor.ts
src/services/friend.service.ts

For example:
- Feature
- Bug
- Refactor …

Myriad official account

---

src/enums/notification-type.enum.ts
src/models/comment.model.ts
src/services/notification.service.ts

For example:
- Feature
- Bug
- Refactor …

Mention people from comment

---

src/models/post.model.ts
src/services/metric.service.ts

For example:
- Feature
- Bug
- Refactor …

added field comment in metric

---

src/migrations/0.0.0.migration.ts

For example:
- Feature
- Bug
- Refactor …

fixed migration

---

src/__tests__/integration/controllers/user-social-media.controller.integration.ts
src/__tests__/unit/user-social-media.controller.unit.ts
src/services/notification.service.ts
src/services/user-social-media.service.ts

For example:
- Feature
- Bug
- Refactor …

Fixed verify user social media

---

src/services/fcm.service.ts
src/services/notification.service.ts

For example:
- Feature
- Bug
- Refactor …

Add body data on firebase notification

---

src/controllers/user.controller.ts
src/enums/activity-log-type.enum.ts

For example:
- Feature
- Bug
- Refactor …

Set display name & username page when user login for the first time is missing

---

src/services/notification.service.ts

For example:
- Feature
- Bug
- Refactor …

refactor notification service

---

src/services/fcm.service.ts

For example:
- Feature
- Bug
- Refactor …

fixed fcm message

---

src/__tests__/acceptance/user.acceptance.ts
src/interceptors/initial-creation.interceptor.ts
src/models/user.model.ts

For example:
- Feature
- Bug
- Refactor …

fixed initial name and username in user model

---

src/interceptors/initial-creation.interceptor.ts

For example:
- Feature
- Bug
- Refactor …

fixed initial username when creating a new user

---

src/interceptors/experience.interceptor.ts
src/models/experience.model.ts

For example:
- Feature
- Bug
- Refactor …

fixed experience

---

src/__tests__/acceptance/comment.acceptance.ts
src/interfaces/metric.interface.ts
src/migrations/1.0.0.migration.ts
src/repositories/post.repository.ts
src/services/metric.service.ts

For example:
- Feature
- Bug
- Refactor …

removed likes and dislikes

---

src/services/notification.service.ts

For example:
- Feature
- Bug
- Refactor …

fixed body message of FCM when commented

---

src/controllers/user-social-media.controller.ts
src/services/social-media.service.ts

For example:
- Feature
- Bug
- Refactor …

error handling if error comes from twitter and reddit

---

src/controllers/post.controller.ts
src/services/social-media.service.ts
src/services/tag.service.ts

For example:
- Feature
- Bug
- Refactor …

fixed count tags

---

.github/workflows/alpha.yml
.github/workflows/beta.yml
.github/workflows/release.yml

Added whitelisted IP

---

src/controllers/index.ts
src/controllers/tip.controller.ts
src/interceptors/initial-creation.interceptor.ts
src/services/currency.service.ts

For example:
- Feature
- Bug
- Refactor …

add feature claim tips

---

src/__tests__/helpers/database.helper.ts
src/models/user.model.ts
src/repositories/user.repository.ts

For example:
- Feature
- Bug
- Refactor …

added user people relation

---

src/__tests__/acceptance/comment.acceptance.ts
src/__tests__/acceptance/post.acceptance.ts
src/__tests__/helpers/database.helper.ts
src/__tests__/helpers/given-instances.ts
src/__tests__/helpers/given-repositories.ts
src/__tests__/integration/controllers/comment.controller.integration.ts
src/controllers/index.ts
src/controllers/post-importer.controller.ts
src/controllers/post.controller.ts
src/interceptors/validate-post-import-url.interceptor.ts
src/migrations/1.0.0.migration.ts
src/models/index.ts
src/models/post-importer.model.ts
src/models/post.model.ts
src/repositories/index.ts
src/repositories/post-importer.repository.ts
src/repositories/post.repository.ts
src/services/notification.service.ts

For example:
- Feature
- Bug
- Refactor …

Added post importer relation

---

src/controllers/user.controller.ts
src/interceptors/initial-creation.interceptor.ts

For example:
- Feature
- Bug
- Refactor …

fix username validation

---

src/controllers/user.controller.ts
src/interceptors/initial-creation.interceptor.ts
src/migrations/1.0.0.migration.ts

For example:
- Feature
- Bug
- Refactor …

Added new migration

---

src/controllers/post.controller.ts
src/interceptors/deleted-document.interceptor.ts
src/interceptors/index.ts
src/interceptors/restricted-post.interceptor.ts

For example:
- Feature
- Bug
- Refactor …

Added interceptor for restricted post

---

src/__tests__/integration/controllers/post.controller.integration.ts
src/__tests__/unit/post.controller.unit.ts
src/controllers/post.controller.ts
src/services/post.service.ts

Reddit lagi error, jadi semua testing yang berhubungan reddit di comment dulu... @irmannmal 
- Feature
- Bug
- Refactor
- Test
- Documentation

hard delete post included the comments

---

src/__tests__/acceptance/post.acceptance.ts
src/interceptors/deleted-document.interceptor.ts

For example:
- Feature
- Bug
- Refactor …

response posts by id

---

src/__tests__/acceptance/post.acceptance.ts
src/interceptors/deleted-document.interceptor.ts

For example:
- Feature
- Bug
- Refactor …

return post without importer when platform is myriad

---

src/interceptors/pagination.interceptor.ts
src/services/friend.service.ts

For example:
- Feature
- Bug
- Refactor …

fixed get importerIds method

---

src/services/friend.service.ts

For example:
- Feature
- Bug
- Refactor …

fixed  timeline query

---

src/migrations/1.0.0.migration.ts

For example:
- Feature
- Bug
- Refactor …

Fix migration

---

src/migrations/1.0.0.migration.ts

For example:
- Feature
- Bug
- Refactor …

added comment to migration files

---

src/__tests__/acceptance/post.acceptance.ts
src/migrations/1.0.0.migration.ts
src/models/post.model.ts

For example:
- Feature
- Bug
- Refactor …

removed default importer

---

src/services/post.service.ts

For example:
- Feature
- Bug
- Refactor …

empty importers when not friend

---

src/interceptors/pagination.interceptor.ts

For example:
- Feature
- Bug
- Refactor …

fixed post query

---

src/__tests__/acceptance/notification.acceptance.ts
src/__tests__/unit/notification.controller.unit.ts
src/controllers/notification.controller.ts
src/interceptors/pagination.interceptor.ts
src/services/notification.service.ts

For example:
- Feature
- Bug
- Refactor …

read single notification

---

src/controllers/friend.controller.ts
src/enums/classname-type.enum.ts
src/interceptors/pagination.interceptor.ts
src/models/friend.model.ts

For example:
- Feature
- Bug
- Refactor …

Added query to include total mutual

---

src/migrations/1.0.0.migration.ts

For example:
- Feature
- Bug
- Refactor …

migration for friends collection

---

src/__tests__/acceptance/deleted-collection.acceptance.ts
src/__tests__/acceptance/post.acceptance.ts
src/__tests__/helpers/database.helper.ts
src/__tests__/helpers/given-instances.ts
src/__tests__/integration/controllers/post.controller.integration.ts
src/__tests__/unit/post.controller.unit.ts
src/controllers/post.controller.ts
src/enums/index.ts
src/enums/post-status-type.enum.ts
src/interceptors/initial-creation.interceptor.ts
src/models/draft-post.model.ts
src/models/index.ts
src/models/post.model.ts
src/repositories/draft-post.repository.ts
src/repositories/index.ts
src/services/post.service.ts

For example:
- Feature
- Bug
- Refactor …

Added new feature draft post

---

src/controllers/index.ts
src/controllers/post.controller.ts
src/controllers/user-draft-post.controller.ts

For example:
- Feature
- Bug
- Refactor …

added endpoint for handle draft post

---

src/interceptors/deleted-document.interceptor.ts
src/interceptors/pagination.interceptor.ts
src/interceptors/restricted-post.interceptor.ts
src/services/post.service.ts

For example:
- Feature
- Bug
- Refactor …

fixed posts

---

src/__tests__/integration/controllers/friend.controller.integration.ts
src/__tests__/integration/controllers/user.controller.integration.ts
src/__tests__/unit/friend.controller.unit.ts
src/__tests__/unit/user.controller.unit.ts
src/controllers/friend.controller.ts
src/controllers/user.controller.ts
src/enums/classname-type.enum.ts
src/interceptors/pagination.interceptor.ts
src/services/metric.service.ts

For example:
- Feature
- Bug
- Refactor …

get detail mutual friends

---

src/interceptors/validate-vote.interceptor.ts
src/services/metric.service.ts

For example:
- Feature
- Bug
- Refactor …

recalculate kudos when removed vote

---

src/interceptors/pagination.interceptor.ts
src/services/experience.service.ts
src/services/friend.service.ts
src/services/tag.service.ts

For example:
- Feature
- Bug
- Refactor …

fixed timeline query

---

src/__tests__/unit/report.controller.unit.ts
src/controllers/report.controller.ts
src/controllers/user-report.controller.ts
src/enums/report-status-type.enum.ts
src/interceptors/report.interceptor.ts
src/models/report.model.ts

For example:
- Feature
- Bug
- Refactor …

fixed report api

---

src/controllers/user-social-media.controller.ts
src/services/user-social-media.service.ts

For example:
- Feature
- Bug
- Refactor …

fixed primary social media

---

src/migrations/1.0.0.migration.ts
src/services/post.service.ts

For example:
- Feature
- Bug
- Refactor …

migration for activity logs collection

---

src/__tests__/acceptance/activity-log.acceptance.ts
src/__tests__/acceptance/post.acceptance.ts
src/__tests__/helpers/database.helper.ts
src/__tests__/helpers/given-instances.ts
src/__tests__/unit/activity-log.controller.unit.ts
src/__tests__/unit/user-social-media.controller.unit.ts
src/controllers/index.ts
src/controllers/leader-board.controller.ts
src/controllers/user.controller.ts
src/enums/classname-type.enum.ts
src/interceptors/experience.interceptor.ts
src/interceptors/initial-creation.interceptor.ts
src/interceptors/pagination.interceptor.ts
src/interceptors/validate-friend-request.interceptor.ts
src/interceptors/validate-post-import-url.interceptor.ts
src/interceptors/validate-vote.interceptor.ts
src/interfaces/metric.interface.ts
src/migrations/1.0.0.migration.ts
src/models/activity-log.model.ts
src/models/index.ts
src/models/leader-board.model.ts
src/models/user.model.ts
src/repositories/index.ts
src/repositories/leader-board.repository.ts
src/repositories/user.repository.ts
src/services/activity-log.service.ts
src/services/currency.service.ts
src/services/metric.service.ts
src/services/user-social-media.service.ts

For example:
- Feature
- Bug
- Refactor …

Refactor activity logs

---

src/services/fcs.service.ts

For example:
- Feature
- Bug
- Refactor …

Make public for image mutation

---

src/services/fcs.service.ts

For example:
- Feature
- Bug
- Refactor …

Fixed video upload destination

---

src/__tests__/integration/controllers/post.controller.integration.ts
src/controllers/post.controller.ts
src/interceptors/report.interceptor.ts

For example:
- Feature
- Bug
- Refactor …

handle deleted imported post

---

src/controllers/storage.controller.ts
src/enums/index.ts
src/enums/upload-type.enum.ts
src/services/fcs.service.ts

For example:
- Feature
- Bug
- Refactor …

Added upload type

---

src/migrations/1.0.0.migration.ts

For example:
- Feature
- Bug
- Refactor …

added account setting migration

---

src/interceptors/experience.interceptor.ts

For example:
- Feature
- Bug
- Refactor …

fixed endpoint delete user experience

---

src/__tests__/helpers/given-instances.ts
src/__tests__/unit/currency.controller.unit.ts
src/application.ts
src/controllers/currency.controller.ts
src/index.ts
src/interceptors/validate-currency.interceptor.ts
src/jobs/update-exchange-rate.job.ts
src/models/currency.model.ts

For example:
- Feature
- Bug
- Refactor …

fixed exchange rates

---

src/application.ts
src/index.ts
src/jobs/index.ts
src/jobs/update-people-profile.job.ts

For example:
- Feature
- Bug
- Refactor …

added cron job for fetching people

---

src/__tests__/acceptance/user-experience.acceptance.ts
src/controllers/user-experience.controller.ts
src/enums/classname-type.enum.ts
src/interceptors/experience.interceptor.ts

For example:
- Feature
- Bug
- Refactor …

fixed experiences

---

src/interceptors/pagination.interceptor.ts
src/services/experience.service.ts
src/services/tag.service.ts

For example:
- Feature
- Bug
- Refactor …

fixed query

---

src/config.ts

For example:
- Feature
- Bug
- Refactor …

Improved default config

---

package.json
src/services/fcs.service.ts
yarn.lock

For example:
- Feature
- Bug
- Refactor …

Removed video converter

---

.maintain/kubernetes/templates/deployment.yaml
README.md
src/components/jwt-authentication.component.ts
src/config.ts
src/keys.ts
src/migrations/0.0.0.migration.ts
src/migrations/1.0.0.migration.ts
src/services/authentication/refreshtoken.service.ts
src/services/currency.service.ts
src/services/friend.service.ts
src/services/notification.service.ts

For example:
- Feature
- Bug
- Refactor …

Cleanup ENV

---

.github/workflows/deploy.yml

change deploy workflow_run

---

.env-template
src/application.ts
src/config.ts
src/controllers/storage.controller.ts

For example:
- Feature
- Bug
- Refactor …

Fixed typo for firebase env

---

src/controllers/notification.controller.ts

For example:
- Feature
- Bug
- Refactor …

added new endpoint for notifaction to mark read multiple notification

---

src/__tests__/acceptance/post.acceptance.ts
src/interceptors/deleted-document.interceptor.ts
src/interceptors/validate-post-import-url.interceptor.ts
src/models/post.model.ts
src/services/post.service.ts

For example:
- Feature
- Bug
- Refactor …

handle blocked user response

---

src/migrations/1.0.0.migration.ts

For example:
- Feature
- Bug
- Refactor …

Remove transaction with DOT as currency

---

src/services/fcs.service.ts

For example:
- Feature
- Bug
- Refactor …

Format image with metadata

---

src/controllers/vote.controller.ts
src/migrations/1.0.0.migration.ts

For example:
- Feature
- Bug
- Refactor …

Removed upvote downvote from notification

---

src/controllers/user-social-media.controller.ts
src/services/notification.service.ts

… social media
For example:
- Feature
- …

added additional referenceId when dis/connecting socialmedia

---

src/services/post.service.ts

For example:
- Feature
- Bug
- Refactor …

Fixed imported post response

---

src/migrations/1.0.0.migration.ts

For example:
- Feature
- Bug
- Refactor …

Added migration for dis/connected social media

---

.github/workflows/deploy.yml

- [MYR-1496] add new deployment env
Added new deployment env
[MYR-1496]: https://blocksphere2020.atlassian.net/browse/MYR-1496?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

MYR-1496: add new deployment env

---

src/__tests__/acceptance/user-social-media.acceptance.ts
src/__tests__/helpers/given-instances.ts
src/__tests__/integration/controllers/user-social-media.controller.integration.ts
src/controllers/user-report.controller.ts
src/services/post.service.ts

For example:
- Feature
- Bug
- Refactor …

fixed report

---

src/interceptors/validate-vote.interceptor.ts

For example:
- Feature
- Bug
- Refactor …

fixed kudos

---

.github/workflows/deploy.yml

- N/A
improve open api & explorer disable

improve open api & explorer disable

---

src/interceptors/initial-creation.interceptor.ts
src/services/currency.service.ts
src/services/post.service.ts

For example:
- Feature
- Bug
- Refactor …

activate auto claim tips

---

src/interceptors/pagination.interceptor.ts

For example:
- Feature
- Bug
- Refactor …

fixed seach experience

---

src/interceptors/report.interceptor.ts

For example:
- Feature
- Bug
- Refactor …

fixed reports

---

src/__tests__/integration/controllers/people.controller.integration.ts
src/__tests__/unit/people.controller.unit.ts
src/controllers/people.controller.ts
src/interceptors/pagination.interceptor.ts
src/services/experience.service.ts
src/services/tag.service.ts

For example:
- Feature
- Bug
- Refactor …

fixed timeline response

---

.github/workflows/deploy.yml

For example:
- Feature
- Bug
- Refactor …

Fixed deployment database connection string

---

src/datasources/mongo.datasource.ts

For example:
- Feature
- Bug
- Refactor …

Fixed database connection string

---

src/application.ts

For example:
- Feature
- Bug
- Refactor …

deactivate migration script

---

.env-template
.github/workflows/deploy.yml
src/config.ts
src/datasources/mongo.datasource.ts

For example:
- Feature
- Bug
- Refactor …

Added mongo protocol options

---

src/controllers/user-experience.controller.ts
src/interceptors/experience.interceptor.ts
src/interceptors/pagination.interceptor.ts
src/services/experience.service.ts

For example:
- Feature
- Bug
- Refactor …

Fixed timeline by experience

---

src/__tests__/acceptance/user-currency.acceptance.ts
src/controllers/user-currency.controller.ts
src/interceptors/validate-currency.interceptor.ts
src/models/user-currency.model.ts
src/models/user.model.ts
src/repositories/user.repository.ts
src/services/experience.service.ts

For example:
- Feature
- Bug
- Refactor …

Add priority field in currency collection

---

src/__tests__/helpers/database.helper.ts
src/controllers/user-currency.controller.ts
src/interceptors/experience.interceptor.ts
src/services/metric.service.ts

For example:
- Feature
- Bug
- Refactor …

Added new endpoint user currency

---

src/interceptors/pagination.interceptor.ts

For example:
- Feature
- Bug
- Refactor …

fixed timeline

---

.github/workflows/deploy.yml

- [ MYR-1482]
add node selector

Add node selector

---

src/application.ts
src/migrate.ts

For example:
- Feature
- Bug
- Refactor …

Created migration script

---

src/services/experience.service.ts

For example:
- Feature
- Bug
- Refactor …

Fixed experience filter

---

src/controllers/post.controller.ts
src/models/platform-post.model.ts

For example:
- Feature
- Bug
- Refactor …

Added new field in platform post model

---

docs/airdrop/README.md
docs/airdrop/leaderboard-distribution.md

For example:
- Feature
- Bug
- Refactor …

Added doc airdrop leaderboard distribution

---

.github/workflows/deploy.yml
docs/airdrop/README.md

Remove ingress staging, testnet, mainnet

Remove ingress staging, testnet, mainnet

---

src/interceptors/authorize.interceptor.ts
src/interceptors/create.interceptor.ts
src/interceptors/delete.interceptor.ts
src/models/comment.model.ts
src/services/metric.service.ts
src/services/vote.service.ts

For example:
- Feature
- Bug
- Refactor …

Added total reply comment in comment metric

---

src/__tests__/acceptance/post.acceptance.ts
src/interceptors/report.interceptor.ts
src/services/notification.service.ts
src/services/post.service.ts

For example:
- Feature
- Bug
- Refactor …

Added function to remove all related post

---

.github/workflows/analyzer.yml
.github/workflows/deployer.yml
.prettierignore
src/interceptors/create.interceptor.ts
src/interceptors/pagination.interceptor.ts
src/services/social-media.service.ts

For example:
- Feature
- Bug
- Refactor …

Added analyzer workflow

---

src/controllers/post.controller.ts

For example:
- Feature
- Bug
- Refactor …

Fixed import post

---

src/services/social-media.service.ts

For example:
- Feature
- Bug
- Refactor …

Fixed parsing text for twitter

---

src/services/metric.service.ts

For example:
- Feature
- Bug
- Refactor …

Fixed post counter

---

src/interceptors/pagination.interceptor.ts
src/services/experience.service.ts

For example:
- Feature
- Bug
- Refactor …

Fixed experience timeline

---

src/interceptors/authorize.interceptor.ts

For example:
- Feature
- Bug
- Refactor …

Fixed decline friend request

---

src/controllers/people.controller.ts

For example:
- Feature
- Bug
- Refactor …

Enabled auth for search people

---

src/interceptors/pagination.interceptor.ts

For example:
- Feature
- Bug
- Refactor …

Fixed search by hashtags

---

src/controllers/experience.controller.ts

For example:
- Feature
- Bug
- Refactor …

Fixed search experience

---

src/services/notification.service.ts

For example:
- Feature
- Bug
- Refactor …

Fixed mention notification

---

src/__tests__/helpers/database.helper.ts
src/__tests__/unit/post.controller.unit.ts
src/interceptors/find-by-id.interceptor.ts
src/interceptors/pagination.interceptor.ts
src/services/experience.service.ts
src/services/post.service.ts
src/services/tag.service.ts

For example:
- Feature
- Bug
- Refactor …

Fixed post and comment when private account

---

src/controllers/comment.controller.ts
src/interceptors/pagination.interceptor.ts
src/services/post.service.ts

For example:
- Feature
- Bug
- Refactor …

Fixed minor bugfix

---

src/__tests__/acceptance/post.acceptance.ts
src/interceptors/validate-post-import-url.interceptor.ts
src/services/currency.service.ts

For example:
- Feature
- Bug
- Refactor …

Changed txHash to blockHash when manually claim tips

---

src/controllers/comment.controller.ts
src/interceptors/find-by-id.interceptor.ts
src/interceptors/pagination.interceptor.ts
src/services/experience.service.ts

For example:
- Feature
- Bug
- Refactor …

fix minor bug

---

src/__tests__/acceptance/friend.acceptance.ts
src/interceptors/authorize.interceptor.ts

For example:
- Feature
- Bug
- Refactor …

Fixed authorize interceptor

---

src/application.ts

For example:
- Feature
- Bug
- Refactor …

Fixed migration storage url

---

src/application.ts

For example:
- Feature
- Bug
- Refactor …

Fixed dependencies

---

src/__tests__/acceptance/post.acceptance.ts
src/__tests__/helpers/database.helper.ts
src/__tests__/unit/post.controller.unit.ts
src/controllers/post.controller.ts
src/interceptors/delete.interceptor.ts
src/services/metric.service.ts
src/services/post.service.ts
src/services/tag.service.ts

For example:
- Feature
- Bug
- Refactor …

Counter should follow current posts

---

src/services/experience.service.ts

For example:
- Feature
- Bug
- Refactor …

Handle for dummy experience

---

src/application.ts
src/controllers/post.controller.ts
src/interceptors/create.interceptor.ts
src/services/post.service.ts
src/services/tag.service.ts

For example:
- Feature
- Bug
- Refactor …

Fixed create tags

---

src/application.ts
src/interceptors/pagination.interceptor.ts
src/services/currency.service.ts
src/services/social-media.service.ts

For example:
- Feature
- Bug
- Refactor …

Fixed user currency priority

---

src/services/authentication/jwt.auth.strategy.ts
src/services/authentication/jwt.service.ts
src/services/currency.service.ts

For example:
- Feature
- Bug
- Refactor …

Escrow transfer validation

---

src/__tests__/acceptance/authentication.acceptance.ts
src/__tests__/acceptance/currency.acceptance.ts
src/interceptors/authentication.interceptor.ts
src/interceptors/create.interceptor.ts
src/services/social-media.service.ts
src/services/tag.service.ts

For example:
- Feature
- Bug
- Refactor …

Hotfix duplicate mongo id

---

src/services/notification.service.ts

For example:
- Feature
- Bug
- Refactor …

Fixed user banned notification

---

src/interceptors/find-by-id.interceptor.ts
src/interceptors/pagination.interceptor.ts
src/interceptors/report.interceptor.ts
src/services/authentication/jwt.auth.strategy.ts
src/services/experience.service.ts
src/services/friend.service.ts
src/services/post.service.ts
src/services/tag.service.ts

For example:
- Feature
- Bug
- Refactor …

Handle timeline with deletedAt

---

src/enums/timelinefilter-type.enum.ts
src/interceptors/create.interceptor.ts
src/interceptors/pagination.interceptor.ts
src/interfaces/metric.interface.ts
src/models/post.model.ts
src/services/metric.service.ts

For example:
- Feature
- Bug
- Refactor …

Filter most tipped

---

src/interceptors/authorize.interceptor.ts
src/interceptors/delete.interceptor.ts

For example:
- Feature
- Bug
- Refactor …

Improve delete comment

---

src/services/social-media.service.ts
src/services/tag.service.ts

For example:
- Feature
- Bug
- Refactor …

Fixed status code 500

---

src/__tests__/acceptance/comment.acceptance.ts
src/services/fcm.service.ts
src/services/notification.service.ts

For example:
- Feature
- Bug
- Refactor …

Fixed reported comment notification

---

src/application.ts
src/services/user-social-media.service.ts

For example:
- Feature
- Bug
- Refactor …

Created migration

---

src/controllers/authentication.controller.ts
src/controllers/friend.controller.ts
src/controllers/post.controller.ts
src/interceptors/pagination.interceptor.ts

For example:
- Feature
- Bug
- Refactor …

Fixed swagger

---

src/__tests__/acceptance/report.acceptance.ts
src/interceptors/delete.interceptor.ts
src/interceptors/experience.interceptor.ts
src/interceptors/find-by-id.interceptor.ts
src/interceptors/pagination.interceptor.ts
src/interceptors/report.interceptor.ts
src/services/experience.service.ts
src/services/metric.service.ts
src/services/post.service.ts
src/services/tag.service.ts

For example:
- Feature
- Bug
- Refactor …

Fixed timeline related

---

src/__tests__/acceptance/post.acceptance.ts
src/controllers/post.controller.ts
src/interceptors/pagination.interceptor.ts
src/interceptors/report.interceptor.ts
src/models/post.model.ts
src/services/authentication/jwt.auth.strategy.ts
src/services/metric.service.ts

For example:
- Feature
- Bug
- Refactor …

Improved for handling banned user

---

src/services/notification.service.ts

For example:
- Feature
- Bug
- Refactor …

Fixed notification

---

src/interceptors/pagination.interceptor.ts

For example:
- Feature
- Bug
- Refactor …

Fixed importers list

---

src/__tests__/acceptance/comment.acceptance.ts
src/application.ts
src/interceptors/create.interceptor.ts
src/interceptors/experience.interceptor.ts
src/interceptors/pagination.interceptor.ts
src/models/notification.model.ts
src/services/notification.service.ts

For example:
- Feature
- Bug
- Refactor …

Refactor notification additional referenceId

---

src/__tests__/acceptance/experience.acceptance.ts
src/__tests__/acceptance/user-experience.acceptance.ts
src/services/experience.service.ts

For example:
- Feature
- Bug
- Refactor …

New field in experience response

---

src/interceptors/report.interceptor.ts

For example:
- Feature
- Bug
- Refactor …

Removed subscribe experience when user banned

---

src/__tests__/acceptance/user.acceptance.ts
src/__tests__/integration/controllers/friend.controller.integration.ts
src/__tests__/unit/friend.controller.unit.ts
src/controllers/friend.controller.ts
src/controllers/user.controller.ts
src/enums/method-type.enum.ts
src/interceptors/pagination.interceptor.ts
src/services/metric.service.ts

For example:
- Feature
- Bug
- Refactor …

Created new endpoint for search friend

---

src/interceptors/pagination.interceptor.ts
src/services/authentication/jwt.auth.strategy.ts

For example:
- Feature
- Bug
- Refactor …

Changed user response

---

src/services/social-media.service.ts

For example:
- Feature
- Bug
- Refactor …

Fixed embedded description

---

src/interceptors/authentication.interceptor.ts
src/interceptors/create.interceptor.ts
src/services/currency.service.ts

For example:
- Feature
- Bug
- Refactor …

Improved autoclaim tips and initial reward

---

src/services/currency.service.ts

For example:
- Feature
- Bug
- Refactor …

Claimed myriad only

---

src/services/social-media.service.ts

For example:
- Feature
- Bug
- Refactor …

Fixed embedded

---

src/interceptors/pagination.interceptor.ts

For example:
- Feature
- Bug
- Refactor …

Fixed search friend by symbol

---

src/__tests__/acceptance/user-experience.acceptance.ts
src/controllers/user-experience.controller.ts
src/interceptors/find-by-id.interceptor.ts
src/services/experience.service.ts

For example:
- Feature
- Bug
- Refactor …

Fixed private experience

---

src/application.ts
src/controllers/authentication.controller.ts
src/controllers/user.controller.ts
src/interceptors/authentication.interceptor.ts
src/models/user.model.ts

For example:
- Feature
- Bug
- Refactor …

Added verified field in user model

---

src/interceptors/pagination.interceptor.ts

For example:
- Feature
- Bug
- Refactor …

Fixed experience query

---

src/__tests__/acceptance/comment.acceptance.ts
src/__tests__/helpers/database.helper.ts
src/interceptors/create.interceptor.ts
src/interceptors/delete.interceptor.ts
src/models/comment.model.ts
src/repositories/comment.repository.ts
src/services/vote.service.ts

For example:
- Feature
- Bug
- Refactor …

Include post in comment collection

---

src/__tests__/acceptance/comment.acceptance.ts
src/__tests__/unit/comment.controller.unit.ts
src/controllers/comment.controller.ts
src/interceptors/delete.interceptor.ts
src/models/comment.model.ts

For example:
- Feature
- Bug
- Refactor …

Feature delete comment

---

src/__tests__/acceptance/user-currency.acceptance.ts
src/application.ts
src/interceptors/create.interceptor.ts
src/interceptors/delete.interceptor.ts

For example:
- Feature
- Bug
- Refactor …

Fixed comment delete by user

---

src/__tests__/acceptance/currency.acceptance.ts
src/interceptors/report.interceptor.ts

For example:
- Feature
- Bug
- Refactor …

Fixed count comment

---

src/controllers/user-social-media.controller.ts
src/interceptors/find-by-id.interceptor.ts
src/services/experience.service.ts
src/services/user-social-media.service.ts

For example:
- Feature
- Bug
- Refactor …

Added deletedAt in people

---

src/__tests__/acceptance/comment.acceptance.ts
src/interceptors/authorize.interceptor.ts
src/interceptors/create.interceptor.ts
src/interceptors/delete.interceptor.ts
src/models/comment.model.ts
src/services/metric.service.ts
src/services/vote.service.ts

For example:
- Feature
- Bug
- Refactor …

Fixed recounting comment when delete by user

---

src/controllers/user-network.controller.ts

For example:
- Feature
- Bug
- Refactor …

Fixed user network endpoint

---

src/services/authentication/jwt.auth.strategy.ts

For example:
- Feature
- Bug
- Refactor …

Handle authentication when getting user wallet

---

src/__tests__/acceptance/post-walletaddress.acceptance.ts
src/controllers/post-walletaddress.controller.ts
src/services/authentication/jwt.auth.strategy.ts

For example:
- Feature
- Bug
- Refactor …

Fix post wallet address

---

src/__tests__/acceptance/transaction.acceptance.ts
src/interceptors/authorize.interceptor.ts

For example:
- Feature
- Bug
- Refactor …

Fixed transaction

---

.github/workflows/analyzer.yml
.github/workflows/builder.yml
.github/workflows/deployer.yml
.github/workflows/tester.yml
.gitignore

N/A
fix github workflow setup gcloud step

fix github workflow setup gcloud step

---

.github/workflows/deployer.yml

For example:
- Feature
- Bug
- Refactor …

add jobs permission

---

package.json
public/index.html

For example:
- Feature
- Bug
- Refactor …

Bump version 2.0.0

---

src/controllers/user-network.controller.ts
src/interceptors/create.interceptor.ts
src/interceptors/update.interceptor.ts

For example:
- Feature
- Bug
- Refactor …

Fixed endpoints

---

.github/workflows/mlc_config.json
src/__tests__/acceptance/user-wallet.acceptance.ts
src/interceptors/authentication.interceptor.ts
src/interceptors/create.interceptor.ts

For example:
- Feature
- Bug
- Refactor …

Fixed primary wallet

---

src/__tests__/helpers/given-instances.ts
src/application.ts
src/controllers/authentication.controller.ts
src/controllers/user-network.controller.ts
src/controllers/user-wallet.controller.ts
src/interceptors/authentication.interceptor.ts
src/interceptors/create.interceptor.ts
src/interceptors/update.interceptor.ts
src/models/wallet.model.ts
src/services/authentication/jwt.service.ts

For example:
- Feature
- Bug
- Refactor …

Fixed connect network

---

src/interceptors/update.interceptor.ts

For example:
- Feature
- Bug
- Refactor …

Fixed change network

---

src/__tests__/acceptance/authentication.acceptance.ts
src/interceptors/authentication.interceptor.ts

For example:
- Feature
- Bug
- Refactor …

Fixed login

---

src/__tests__/acceptance/currency.acceptance.ts
src/__tests__/acceptance/transaction.acceptance.ts
src/__tests__/helpers/database.helper.ts
src/__tests__/helpers/given-instances.ts
src/__tests__/helpers/given-repositories.ts
src/__tests__/unit/currency.controller.unit.ts
src/controllers/currency.controller.ts
src/controllers/index.ts
src/controllers/transaction.controller.ts
src/controllers/user-currency.controller.ts
src/controllers/wallet.controller.ts
src/enums/controller-type.enum.ts
src/interceptors/authentication.interceptor.ts
src/interceptors/authorize.interceptor.ts
src/interceptors/delete.interceptor.ts
src/interceptors/pagination.interceptor.ts
src/interceptors/update.interceptor.ts
src/models/currency.model.ts
src/models/index.ts
src/models/network.model.ts
src/models/transaction.model.ts
src/models/user-currency.model.ts
src/models/user.model.ts
src/repositories/index.ts
src/repositories/user-currency.repository.ts
src/repositories/user.repository.ts
src/services/metric.service.ts
src/services/network.service.ts

For example:
- Feature
- Bug
- Refactor …

Manage currency feature

---

src/controllers/wallet.controller.ts
src/interceptors/authentication.interceptor.ts
src/interceptors/create.interceptor.ts
src/interceptors/pagination.interceptor.ts
src/interceptors/update.interceptor.ts
src/services/currency.service.ts

For example:
- Feature
- Bug
- Refactor …

Fixed user currency

---

src/application.ts
src/models/currency.model.ts

For example:
- Feature
- Bug
- Refactor …

Updated migration

---

src/interceptors/pagination.interceptor.ts

For example:
- Feature
- Bug
- Refactor …

Fixed transaction query

---

src/__tests__/acceptance/user-social-media.acceptance.ts
src/__tests__/helpers/given-instances.ts
src/controllers/user-social-media.controller.ts
src/interceptors/authorize.interceptor.ts
src/models/user-verification.model.ts
src/services/social-media.service.ts

For example:
- Feature
- Bug
- Refactor …

Improved verify socialmedia

---

src/controllers/index.ts
src/controllers/server.controller.ts

For example:
- Feature
- Bug
- Refactor …

Created server controller

---

src/application.ts
src/models/network.model.ts

For example:
- Feature
- Bug
- Refactor …

Added new field in network model

---

.github/workflows/builder.yml
.github/workflows/deployer.yml
.maintain/docker/Dockerfile

- [MYR-1911]
add docker build args (NODE_ENV)
[MYR-1911]: https://blocksphere2020.atlassian.net/browse/MYR-1911?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

add docker build args

---

.github/workflows/deployer.yml

- N/A
fix helm install command

fix helm install command

---

src/application.ts
src/interceptors/authentication.interceptor.ts

For example:
- Feature
- Bug
- Refactor …

Fixed validate near address

---

src/interceptors/authentication.interceptor.ts

For example:
- Feature
- Bug
- Refactor …

Fixed validate nearAddress

---

.github/workflows/builder.yml
.maintain/docker/Dockerfile

- [MYR-1919]
improve NODE_ENV
[MYR-1919]: https://blocksphere2020.atlassian.net/browse/MYR-1919?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Revert "add docker build args"

---

src/__tests__/acceptance/user-social-media.acceptance.ts
src/controllers/user-social-media.controller.ts
src/interceptors/create.interceptor.ts

For example:
- Feature
- Bug
- Refactor …

Fixed claim reference when verify social media

---

src/models/network.model.ts
src/services/network.service.ts
src/utils/formated-balance.ts

For example:
- Feature
- Bug
- Refactor …

Fixed network model

---

src/enums/reference-type.enum.ts
src/interceptors/create.interceptor.ts
src/services/network.service.ts

For example:
- Feature
- Bug
- Refactor …

Fixed claim reference when connect to social media

---

.github/workflows/deployer.yml

For example:
- Feature
- Bug
- Refactor …

remove unused env

---

src/__tests__/integration/controllers/transaction.controller.integration.ts
src/__tests__/unit/transaction.controller.unit.ts
src/controllers/transaction.controller.ts
src/interceptors/authorize.interceptor.ts

For example:
- Feature
- Bug
- Refactor …

Added new transaction endpoint

---

src/interceptors/experience.interceptor.ts

For example:
- Feature
- Bug
- Refactor …

Fixed experience counter

---

.github/workflows/mlc_config.json
src/__tests__/acceptance/user-experience.acceptance.ts
src/interceptors/experience.interceptor.ts

For example:
- Feature
- Bug
- Refactor …

Experience interceptor clean code

---

src/__tests__/acceptance/authentication.acceptance.ts
src/__tests__/acceptance/post-walletaddress.acceptance.ts
src/__tests__/acceptance/user-experience.acceptance.ts
src/__tests__/acceptance/user-wallet.acceptance.ts
src/__tests__/helpers/database.helper.ts
src/__tests__/helpers/given-instances.ts
src/controllers/index.ts
src/controllers/wallet-network.controller.ts
src/controllers/wallet.controller.ts
src/controllers/walletaddress.controller.ts
src/interceptors/authentication.interceptor.ts
src/interceptors/create.interceptor.ts
src/interceptors/pagination.interceptor.ts
src/interceptors/update.interceptor.ts
src/models/wallet.model.ts
src/repositories/wallet.repository.ts
src/services/authentication/jwt.auth.strategy.ts
src/services/friend.service.ts

For example:
- Feature
- Bug
- Refactor …

Include network in wallet model

---

.github/workflows/tester.yml

- [MYR-1966] 
improve testing pipeline
[MYR-1966]: https://blocksphere2020.atlassian.net/browse/MYR-1966?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

improve testing pipeline

---

src/interceptors/experience.interceptor.ts

For example:
- Feature
- Bug
- Refactor …

Fixed experience when unsubscribe

---

src/__tests__/acceptance/authentication.acceptance.ts
src/__tests__/acceptance/post-walletaddress.acceptance.ts
src/__tests__/acceptance/user-wallet.acceptance.ts
src/__tests__/helpers/given-instances.ts
src/controllers/walletaddress.controller.ts
src/enums/index.ts
src/enums/network-type.enum.ts
src/interceptors/authentication.interceptor.ts
src/services/network.service.ts

For example:
- Feature
- Bug
- Refactor …

Fixed login when switch network

---

.github/workflows/analyzer.yml
.github/workflows/builder.yml

- [MYR-1966]
Improvement docker build, re-tag if the commit hash is the same
[MYR-1966]: https://blocksphere2020.atlassian.net/browse/MYR-1966?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

improve docker build

---

.gitignore
src/application.ts
src/controllers/storage.controller.ts
src/services/fcs.service.ts

For example:
- Feature
- Bug
- Refactor …

Allowed local storage when GCS is diabled

---

.eslintignore
.eslintrc.js
seed-data/default-network-currencies.json
seed-data/default-user-wallet.json
src/__tests__/acceptance/authentication.acceptance.ts
src/__tests__/acceptance/user-wallet.acceptance.ts
src/__tests__/acceptance/user.acceptance.ts
src/__tests__/acceptance/walletaddress.acceptance.ts
src/__tests__/helpers/given-instances.ts
src/application.ts
src/controllers/authentication.controller.ts
src/controllers/user-experience.controller.ts
src/controllers/vote.controller.ts
src/controllers/walletaddress.controller.ts
src/enums/index.ts
src/enums/wallet-type.enum.ts
src/interceptors/authentication.interceptor.ts
src/interceptors/create.interceptor.ts
src/interceptors/delete.interceptor.ts
src/interceptors/pagination.interceptor.ts
src/interceptors/update.interceptor.ts
src/models/credential.model.ts
src/models/network.model.ts
src/models/user-wallet.model.ts
src/models/user.model.ts
src/models/wallet.model.ts
src/services/currency.service.ts
src/services/experience.service.ts
src/services/network.service.ts
src/utils/validate-account.ts

For example:
- Feature
- Bug
- Refactor …

Refactor wallet

---

src/services/notification.service.ts

For example:
- Feature
- Bug
- Refactor …

Added new field in additionalReferenceId

---

src/__tests__/acceptance/friend.acceptance.ts
src/__tests__/acceptance/user.acceptance.ts
src/enums/timelinefilter-type.enum.ts
src/interceptors/delete.interceptor.ts
src/interceptors/pagination.interceptor.ts
src/interceptors/update.interceptor.ts
src/models/user.model.ts

For example:
- Feature
- Bug
- Refactor …

Prioritize friend to be on top of list

---

src/interceptors/authentication.interceptor.ts
src/interceptors/create.interceptor.ts
src/interceptors/update.interceptor.ts
src/services/currency.service.ts

For example:
- Feature
- Bug
- Refactor …

Fixed user currency creation

---

src/__tests__/helpers/database.helper.ts
src/application.ts
src/controllers/server.controller.ts
src/enums/controller-type.enum.ts
src/enums/method-type.enum.ts
src/interceptors/authentication.interceptor.ts
src/interceptors/authorize.interceptor.ts
src/interceptors/create.interceptor.ts
src/interceptors/delete.interceptor.ts
src/models/index.ts
src/models/server.model.ts
src/repositories/index.ts
src/repositories/server.repository.ts
src/services/metric.service.ts

For example:
- Feature
- Bug
- Refactor …

Create endpoint for server info

---

src/__tests__/acceptance/experience-post.acceptance.ts
src/__tests__/helpers/given-instances.ts
src/__tests__/helpers/given-repositories.ts
src/controllers/experience-post.controller.ts
src/enums/method-type.enum.ts
src/interceptors/authorize.interceptor.ts
src/interceptors/create.interceptor.ts
src/services/experience.service.ts

For example:
- Feature
- Bug
- Refactor …

Added new endpoint for batch creation experience post

---

src/__tests__/acceptance/post.acceptance.ts
src/interceptors/delete.interceptor.ts
src/interceptors/pagination.interceptor.ts
src/services/post.service.ts

For example:
- Feature
- Bug
- Refactor …

Fixed experience when deleting

---

src/interceptors/pagination.interceptor.ts

For example:
- Feature
- Bug
- Refactor …

Added filter by user when fetch transaction

---

package.json
public/index.html

For example:
- Feature
- Bug
- Refactor …

Updated version to 2.1.1

---

src/interceptors/pagination.interceptor.ts

For example:
- Feature
- Bug
- Refactor …

Fixed filter when fetch transaction

---

src/interceptors/pagination.interceptor.ts

For example:
- Feature
- Bug
- Refactor …

Fixed query post by hashtag

---

src/utils/validate-account.ts

For example:
- Feature
- Bug
- Refactor …

Fixed authentication when login with polkadot js

---

src/services/experience.service.ts

For example:
- Feature
- Bug
- Refactor …

Fixed query post by hashtag in experience timeline

---

src/__tests__/acceptance/user-social-media.acceptance.ts
src/controllers/user-social-media.controller.ts
src/controllers/wallet.controller.ts
src/interceptors/create.interceptor.ts
src/interceptors/delete.interceptor.ts
src/interceptors/pagination.interceptor.ts
src/services/authentication/jwt.auth.strategy.ts
src/services/currency.service.ts
src/services/network.service.ts
src/services/user-social-media.service.ts

For example:
- Feature
- Bug
- Refactor …

Remove claim reference from API

---

src/__tests__/acceptance/user-wallet.acceptance.ts
src/controllers/user-social-media.controller.ts
src/interceptors/create.interceptor.ts
src/models/user-social-media.model.ts
src/services/user-social-media.service.ts

For example:
- Feature
- Bug
- Refactor …

Fixed connected social media and account

---

src/interceptors/create.interceptor.ts
src/interceptors/pagination.interceptor.ts
src/interfaces/metric.interface.ts
src/models/server.model.ts
src/services/metric.service.ts
src/services/social-media.service.ts

For example:
- Feature
- Bug
- Refactor …

Fix metric field name for server info

---

.github/workflows/deployer.yml

- [MYR-2113]
Add sleuth webhook
[MYR-2113]: https://blocksphere2020.atlassian.net/browse/MYR-2113?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add sleuth webhook

---

src/controllers/user-social-media.controller.ts
src/controllers/user-wallet.controller.ts
src/interceptors/create.interceptor.ts
src/services/network.service.ts

For example:
- Feature
- Bug
- Refactor …

Handle verify account when not using blockchain

---

src/interceptors/create.interceptor.ts
src/services/user-social-media.service.ts

For example:
- Feature
- Bug
- Refactor …

Fixed verify account

---

package.json
src/interceptors/pagination.interceptor.ts
src/services/authentication/jwt.auth.strategy.ts
src/utils/generate-object-id.ts
yarn.lock

For example:
- Feature
- Bug
- Refactor …

Hotfix authentication as demo user

---

src/interceptors/pagination.interceptor.ts
src/services/experience.service.ts

For example:
- Feature
- Bug
- Refactor …

Fixed query for all post

---

src/__tests__/integration/controllers/experience.controller.integration.ts
src/__tests__/unit/experience.controllet.unit.ts
src/__tests__/unit/post.controller.unit.ts
src/controllers/experience.controller.ts
src/controllers/post.controller.ts
src/interceptors/find-by-id.interceptor.ts
src/interceptors/pagination.interceptor.ts
src/services/post.service.ts

For example:
- Feature
- Bug
- Refactor …

Fixed findById query post

---

src/interceptors/pagination.interceptor.ts

For example:
- Feature
- Bug
- Refactor …

Fixed post timeline all

---

src/interceptors/update.interceptor.ts

For example:
- Feature
- Bug
- Refactor …

Fixed minor bug when update visibility

---

src/__tests__/acceptance/experience.acceptance.ts
src/__tests__/acceptance/user-experience.acceptance.ts
src/__tests__/helpers/database.helper.ts
src/__tests__/integration/controllers/experience.controller.integration.ts
src/__tests__/unit/experience.controllet.unit.ts
src/controllers/experience.controller.ts
src/controllers/post.controller.ts
src/interceptors/find-by-id.interceptor.ts
src/interceptors/pagination.interceptor.ts
src/interceptors/update.interceptor.ts
src/services/currency.service.ts
src/services/experience.service.ts
src/services/network.service.ts

For example:
- Feature
- Bug
- Refactor …

Handle Account Privacy

---

package.json
public/index.html
src/interceptors/create.interceptor.ts
src/services/post.service.ts
src/services/social-media.service.ts

For example:
- Feature
- Bug
- Refactor …

Updated version to 2.1.3

---

src/interceptors/pagination.interceptor.ts

For example:
- Feature
- Bug
- Refactor …

Fixed pagination

---

src/interceptors/pagination.interceptor.ts
src/models/experience-post.model.ts
src/services/authentication/jwt.auth.strategy.ts
src/services/metric.service.ts
src/services/report.service.ts

For example:
- Feature
- Bug
- Refactor …

Handle deleted post in experience

---

src/services/report.service.ts

For example:
- Feature
- Bug
- Refactor …

Removed post in experience when account banned

---

src/interceptors/pagination.interceptor.ts

For example:
- Feature
- Bug
- Refactor …

Fixed friend total mutual

---

src/interceptors/pagination.interceptor.ts

For example:
- Feature
- Bug
- Refactor …

Fixed get experience post

---

src/controllers/experience.controller.ts
src/controllers/people.controller.ts
src/interceptors/find-by-id.interceptor.ts
src/interceptors/pagination.interceptor.ts
src/services/experience.service.ts
src/services/metric.service.ts
src/services/post.service.ts

For example:
- Feature
- Bug
- Refactor …

fix: nullable query

---

src/interceptors/create.interceptor.ts
src/interceptors/pagination.interceptor.ts
src/interceptors/update.interceptor.ts
src/services/post.service.ts
src/services/social-media.service.ts
src/utils/url.utils.ts

MYR-2198: Imported Reddit post failed
For example:
Please describe the tests that you ran to verify your changes. Please also note any relevant details for your test …

fix: imported reddit post

---

src/controllers/walletaddress.controller.ts
src/interceptors/find-by-id.interceptor.ts
src/interceptors/pagination.interceptor.ts

[MYR-2208: Implement near tipping](https://blocksphere2020.atlassian.net/browse/MYR-2208)
For example:
- I couldn't figure out a way to center the button with flexbox (TODO)
Please describe the tests that you ran to verify your changes. …

feat: implement tipping with near

---

src/controllers/walletaddress.controller.ts
src/interceptors/create.interceptor.ts
src/interceptors/find-by-id.interceptor.ts
src/interceptors/pagination.interceptor.ts

For example:
- Feature
- Bug
- Refactor …

fix: reporttype in comment when deleted

---

src/controllers/walletaddress.controller.ts

For example:
- Feature
- Bug
- Refactor …

fix: disabled tipping with near

---

src/interceptors/pagination.interceptor.ts

For example:
- Feature
- Bug
- Refactor …

fix: deleleted comment

---

src/__tests__/acceptance/experience-post.acceptance.ts
src/__tests__/acceptance/post.acceptance.ts
src/__tests__/helpers/given-instances.ts
src/controllers/post.controller.ts
src/controllers/user-draft-post.controller.ts
src/interceptors/create.interceptor.ts
src/interceptors/delete.interceptor.ts
src/interceptors/pagination.interceptor.ts
src/models/draft-post.model.ts
src/models/post.model.ts
src/repositories/draft-post.repository.ts
src/services/experience.service.ts
src/services/friend.service.ts
src/services/post.service.ts
src/services/tag.service.ts

[MYR-2213: Experience Timeline to chronological](https://blocksphere2020.atlassian.net/browse/MYR-2213)
For example:
Please describe the tests that you ran to verify your …

fix: timeline in chronological order

---

src/interceptors/find-by-id.interceptor.ts
src/interceptors/pagination.interceptor.ts

For example:
- Feature
- Bug
- Refactor …

fix: renamed user banned

---

package.json
public/index.html

For example:
- Feature
- Bug
- Refactor …

chore: bump version to 2.1.5

---

src/__tests__/acceptance/friend.acceptance.ts
src/__tests__/acceptance/notification.acceptance.ts
src/__tests__/helpers/given-instances.ts
src/__tests__/unit/notification.controller.unit.ts
src/services/notification.service.ts

- fix notification wording
- https://blocksphere2020.atlassian.net/browse/MYR-2236
- Feature
- Bug
- Refactor
- Test
- Documentation

fix: notification wording

---

src/__tests__/acceptance/post.acceptance.ts
src/__tests__/helpers/database.helper.ts
src/__tests__/helpers/given-instances.ts
src/__tests__/unit/post.controller.unit.ts
src/controllers/index.ts
src/controllers/post-experience.controller.ts
src/controllers/post.controller.ts
src/enums/controller-type.enum.ts
src/interceptors/find-by-id.interceptor.ts
src/interceptors/pagination.interceptor.ts
src/models/post.model.ts
src/repositories/post.repository.ts
src/services/metric.service.ts
src/services/post.service.ts

[MYR-2250: Add Experience Name Under Post](https://blocksphere2020.atlassian.net/browse/MYR-2250)
For example:
Please describe the tests that you ran to verify your …

feat: added experience under post name

---

src/application.ts
src/controllers/server.controller.ts
src/models/server.model.ts

[MYR-2255: New field in server model](https://blocksphere2020.atlassian.net/browse/MYR-2255)
For example:
Please describe the tests that you ran to verify your changes. …

fix: new field in server model

---

src/controllers/claim-reference.controller.ts
src/controllers/user-currency.controller.ts
src/controllers/walletaddress.controller.ts
src/interceptors/authorize.interceptor.ts
src/interceptors/pagination.interceptor.ts
src/interceptors/update.interceptor.ts
src/models/claim-reference.model.ts

[MYR-2262: Activate tipping with NEAR for non myriad user](https://blocksphere2020.atlassian.net/browse/MYR-2262)
For example:
Please describe the tests that you ran to …

feat: activate tipping with near

---

.github/pull_request_template.md
.github/workflows/analyzer.yml
.github/workflows/builder.yml
.github/workflows/create-tags.yml
.github/workflows/deployer.yml
.github/workflows/release.yml
.github/workflows/tester.yml
.github/workflows/update-version.yml
src/interceptors/authorize.interceptor.ts

fix: authorization in user currency

---

package.json
public/index.html

chore: bump version to 2.1.6

---

src/controllers/walletaddress.controller.ts

fix: tipsBalanceInfo serverId

---

.github/workflows/deployer.yml

Improve ingress annotations
N/A

cd: improve ingress

---

src/controllers/transaction.controller.ts

fix: update transaction

---

package.json
public/index.html
src/controllers/claim-reference.controller.ts
src/interfaces/transaction-summary.interface.ts
src/services/network.service.ts

- Implement claim reference in myriad network
- https://blocksphere2020.atlassian.net/browse/MYR-2288

feat: claim reference for network myriad

---

src/controllers/experience.controller.ts

- Handle experience belongs to banned account
- https://blocksphere2020.atlassian.net/browse/MYR-2123

fix: typo deletedAt on experience

---

src/__tests__/acceptance/user-experience.acceptance.ts
src/interceptors/create.interceptor.ts
src/services/experience.service.ts

- Remove maximum total subscribe experience validation
[MYR-2318: For User on Experience to be able to subscribe to more than 10 People](https://blocksphere2020.atlassian.net/browse/MYR-2318)

fix: validate total experience created by user

---

src/controllers/notification.controller.ts
src/interceptors/authorize.interceptor.ts
src/services/notification.service.ts

- Handle unlimited read-all notifications
- Fix receiving notification tips 
[MYR-2314: Notification doesn't Clear up when mark as read is clicked](https://blocksphere2020.atlassian.net/browse/MYR-2314)
[MYR-2307: Notification when receiving tips](https://blocksphere2020.atlassian.net/browse/MYR-2307)

fix: read all notifications

---

src/controllers/user-social-media.controller.ts
src/models/user-verification.model.ts

- Set Interval when verifying social media
[MYR-2310: Error when verifying social media](https://blocksphere2020.atlassian.net/browse/MYR-2310)

fix: setInterval when verifying social media

---

src/services/network.service.ts

- change method when claim reference
[MYR-2346: Improve claim reference](https://blocksphere2020.atlassian.net/browse/MYR-2346)

fix: change blockchain claim reference method

---

src/__tests__/acceptance/user-experience.acceptance.ts
src/interceptors/pagination.interceptor.ts
src/interfaces/meta-pagination.interface.ts

- Counting total owned experiences
[MYR-2318: For User on Experience to be able to subscribe to more than 10 People](https://blocksphere2020.atlassian.net/browse/MYR-2318)

fix: added additional data for user experiences

---

package.json
public/index.html
src/__tests__/acceptance/post.acceptance.ts
src/interceptors/create.interceptor.ts
src/interfaces/asset.interface.ts
src/services/social-media.service.ts

- Include different image resolutions for imported post
- Bump version to 2.1.8
[MYR-2322: Improvement image resolution in imported post](https://blocksphere2020.atlassian.net/browse/MYR-2322)

fix: different image sizes for imported post

---

src/controllers/wallet.controller.ts
src/interceptors/find-by-id.interceptor.ts
src/models/user-currency.model.ts
src/models/user.model.ts
src/repositories/user.repository.ts

- Added relation user has many user currencies
[MYR-2385: Create user - userCurrencies relation](https://blocksphere2020.atlassian.net/browse/MYR-2385)

fix: include user currencies in user response

---

src/__tests__/helpers/database.helper.ts
src/interceptors/pagination.interceptor.ts
src/models/people.model.ts
src/models/transaction.model.ts
src/repositories/people.repository.ts
src/services/currency.service.ts
src/services/fcm.service.ts
src/services/notification.service.ts
src/services/user-social-media.service.ts

[MYR-2357: Generate Onboard User Reward](https://blocksphere2020.atlassian.net/browse/MYR-2357)

feat: airdrop onboard user

---

package.json
public/index.html
src/controllers/server.controller.ts
src/models/people.model.ts
src/models/server.model.ts
src/services/fcm.service.ts
src/services/notification.service.ts

- Added new field in server model
- API bump version to 2.1.9
[MYR-2375: Replace Myriad testnet logo](https://blocksphere2020.atlassian.net/browse/MYR-2375)

fix: added new field in server model

---

src/services/fcm.service.ts
src/services/notification.service.ts

set notification for data only
https://blocksphere2020.atlassian.net/browse/MYR-2418

feat: set notification for data only

---

src/services/fcm.service.ts

fix fcm payload object data
N/A

fix: fcm payload

---

package.json
public/index.html
src/services/social-media.service.ts

- Fix failed get image from reddit post
- Bump version to 2.1.10
[MYR-2425: Failed to import reddit post with multiple pictures](https://blocksphere2020.atlassian.net/browse/MYR-2425)

fix: failed to import reddit post with multiple images

---

src/interceptors/authorize.interceptor.ts

- Remove condition when status is pending
[MYR-2426: Handle cancel friend request](https://blocksphere2020.atlassian.net/browse/MYR-2426)

fix: handle cancel friend request from requestor

---

package.json
src/interceptors/authentication.interceptor.ts
src/interceptors/create.interceptor.ts
src/interceptors/update.interceptor.ts
src/utils/near-api-js.ts
src/utils/polkadotJs-utils.ts
src/utils/validate-account.ts
yarn.lock

- Added accessKey validation
[MYR-2460: Improve near auth security](https://blocksphere2020.atlassian.net/browse/MYR-2460)

fix: improve near auth security

---

package.json
public/index.html

chore: bump version to 2.1.12

---

src/interceptors/authentication.interceptor.ts
src/interceptors/create.interceptor.ts
src/interceptors/update.interceptor.ts
src/utils/near-api-js.ts
src/utils/validate-account.ts

chore: enabled logging

---

src/interceptors/pagination.interceptor.ts

fix: airdrop user onboarding to monthly
https://blocksphere2020.atlassian.net/browse/MYR-2462

fix: airdrop user onboarding to monthly

---

src/models/network.model.ts

- Add 2nd WalletURL
- Add case for mynearwallet when auth
[MYR-2468: Add new field in network model](https://blocksphere2020.atlassian.net/browse/MYR-2468)

fix: added new field walletURL in network document

---

src/models/network.model.ts

fix: renamed walletURL 

---

package.json
public/index.html

chore: bump version to 2.1.14

---

src/controllers/post.controller.ts
src/enums/timelinefilter-type.enum.ts
src/interceptors/pagination.interceptor.ts
src/services/friend.service.ts

- [MYR-2522: Hardening API security](https://blocksphere2020.atlassian.net/browse/MYR-2522)
- [MYR-2531: Improved GET /posts security](https://blocksphere2020.atlassian.net/browse/MYR-2531)

fix: improve security for GET /posts

---

package.json
public/index.html

chore: bump version to 2.1.15

---

src/interceptors/pagination.interceptor.ts

https://blocksphere2020.atlassian.net/browse/MYR-2531

fix: improved GET /posts security

---

src/interceptors/pagination.interceptor.ts

fix: improve security

---

src/__tests__/acceptance/post.acceptance.ts
src/__tests__/integration/controllers/user-social-media.controller.integration.ts
src/__tests__/unit/user-social-media.controller.unit.ts
src/controllers/server.controller.ts
src/controllers/user-social-media.controller.ts
src/interceptors/create.interceptor.ts
src/interfaces/metric.interface.ts
src/models/server.model.ts
src/models/user.model.ts
src/services/metric.service.ts
src/services/notification.service.ts
src/services/report.service.ts

https://blocksphere2020.atlassian.net/browse/MYR-2561

fix: added new metric for median

---

src/__tests__/acceptance/transaction.acceptance.ts
src/__tests__/helpers/database.helper.ts
src/__tests__/integration/controllers/transaction.controller.integration.ts
src/application.ts
src/controllers/transaction.controller.ts
src/interceptors/authentication.interceptor.ts
src/interceptors/create.interceptor.ts
src/interceptors/pagination.interceptor.ts
src/models/transaction.model.ts
src/repositories/transaction.repository.ts
src/services/currency.service.ts
src/services/notification.service.ts

[MYR-2547: Remapping Transaction Data by UserID](https://blocksphere2020.atlassian.net/browse/MYR-2547)

fix: remapping Transaction Data by UserID

---

src/controllers/server.controller.ts
src/interceptors/create.interceptor.ts
src/interfaces/metric.interface.ts
src/services/metric.service.ts
src/services/notification.service.ts

https://blocksphere2020.atlassian.net/browse/MYR-2547

fix: improved create notification when send transaction

---

src/controllers/wallet.controller.ts
src/interceptors/authorize.interceptor.ts
src/interceptors/delete.interceptor.ts

https://blocksphere2020.atlassian.net/browse/MYR-2534

fix: remove wallet without delete user currency

---

src/controllers/user.controller.ts
src/enums/method-type.enum.ts
src/interceptors/find-by-id.interceptor.ts

fix: added endpoint to get current user

---

src/interceptors/find-by-id.interceptor.ts

fix: improved query get user

---

src/controllers/post-experience.controller.ts
src/interceptors/pagination.interceptor.ts
src/services/experience.service.ts
src/services/metric.service.ts

https://blocksphere2020.atlassian.net/browse/MYR-2531

fix: improved query for timeline type of experience

---

src/__tests__/unit/currency.controller.unit.ts
src/controllers/currency.controller.ts
src/interceptors/pagination.interceptor.ts
src/interfaces/metric.interface.ts
src/services/metric.service.ts

fix: added new data for server metric

---

src/__tests__/unit/currency.controller.unit.ts
src/controllers/currency.controller.ts
src/controllers/friend.controller.ts
src/controllers/index.ts
src/controllers/statistic.controller.ts
src/interceptors/pagination.interceptor.ts

fix: user growth stats

---

src/application.ts
src/controllers/server.controller.ts
src/models/server.model.ts
src/services/index.ts
src/services/server.service.ts

https://blocksphere2020.atlassian.net/browse/MYR-2598

feat: added average metric

---

src/controllers/storage.controller.ts
src/interceptors/authorize.interceptor.ts

https://blocksphere2020.atlassian.net/browse/MYR-2599

fix: change storage endpoint to general endpoint

---

package.json
src/interceptors/authentication.interceptor.ts
src/models/server.model.ts
src/utils/near-api-js.ts

fix: authentication with near

---

src/controllers/authentication.controller.ts
src/interceptors/find-by-id.interceptor.ts

https://blocksphere2020.atlassian.net/browse/MYR-2641

fix: check user by email

---

src/controllers/authentication.controller.ts
src/interceptors/authentication.interceptor.ts
src/interceptors/create.interceptor.ts
src/models/user.model.ts
src/services/authentication/jwt.auth.strategy.ts

fix: added flagging for lite version

---

src/models/user-otp.model.ts
src/services/user-otp.service.ts

fix: revalidate OTP
https://blocksphere2020.atlassian.net/browse/MYR-2680

fix: revalidate OTP

---

src/__tests__/acceptance/friend.acceptance.ts
src/__tests__/acceptance/user-experience.acceptance.ts
src/interceptors/authorize.interceptor.ts
src/interceptors/create.interceptor.ts

- https://blocksphere2020.atlassian.net/browse/MYR-2676
- https://blocksphere2020.atlassian.net/browse/MYR-2677

fix: set limitation for lite version

---

src/application.ts
src/controllers/admin.controller.ts
src/controllers/claim-reference.controller.ts
src/controllers/index.ts
src/controllers/user/index.ts
src/controllers/user/setting.controller.ts
src/enums/method-type.enum.ts
src/interceptors/authentication.interceptor.ts
src/models/change-email-request.model.ts
src/models/index.ts
src/models/user-otp.model.ts
src/models/user.model.ts
src/repositories/change-email-request.repository.ts
src/repositories/index.ts
src/services/authentication/jwt.auth.strategy.ts
src/services/user-otp.service.ts
src/services/user.service.ts

https://blocksphere2020.atlassian.net/browse/MYR-2671

feat: edit email

---

src/__tests__/acceptance/comment.acceptance.ts
src/__tests__/acceptance/post.acceptance.ts
src/interceptors/create.interceptor.ts

https://blocksphere2020.atlassian.net/browse/MYR-2678
https://blocksphere2020.atlassian.net/browse/MYR-2675

fix: set limit on create post, import post, and comment

---

src/controllers/user/setting.controller.ts
src/services/authentication/jwt.auth.strategy.ts
src/services/user-otp.service.ts
src/services/user.service.ts

https://blocksphere2020.atlassian.net/browse/MYR-2697

fix: added remove email endpoint

---

src/interceptors/create.interceptor.ts

- https://blocksphere2020.atlassian.net/browse/MYR-2707

fix: connect wallet in lite version

---

src/interceptors/create.interceptor.ts
src/models/experience.model.ts
src/services/user-otp.service.ts

fix: extend timeout time

---

package.json
src/interceptors/create.interceptor.ts
src/interceptors/update.interceptor.ts

fix: remove required people on create experiences

---

package.json

chore: bump version to 2.2.0

---

src/__tests__/helpers/given-instances.ts
src/controllers/authentication.controller.ts
src/interceptors/authentication.interceptor.ts
src/models/request-create-new-user-by-email.model.ts
src/models/user.model.ts
src/repositories/index.ts
src/repositories/request-create-new-user-by-email.repository.ts
src/services/user-otp.service.ts

- https://blocksphere2020.atlassian.net/browse/MYR-2725

fix: refactor login flow by email

---

src/controllers/authentication.controller.ts

fix: changed signup by email response

---

src/application.ts

fix: remove exchange rates job

---

src/controllers/user/setting.controller.ts
src/models/user.model.ts
src/services/user.service.ts

fix: fixed update email

---

src/interfaces/metric.interface.ts
src/services/metric.service.ts

feat: total email on server matric
https://blocksphere2020.atlassian.net/browse/MYR-2755

feat: total email on server matric

---

src/services/user-otp.service.ts

- https://blocksphere2020.atlassian.net/browse/MYR-2754

fix: fixed add email

---

package.json

chore: bump version to 2.2.1

---

src/__tests__/acceptance/walletaddress.acceptance.ts
src/controllers/wallet-address.controller.ts
src/services/authentication/jwt.auth.strategy.ts

fix: rename endpoint for reference walletaddress

---

package.json

chore: bump version to 2.2.2

---

src/services/metric.service.ts

fix: count user email on server matric
https://blocksphere2020.atlassian.net/browse/MYR-2755

fix: count user email on server matric

---

src/__tests__/acceptance/authentication.acceptance.ts
src/controllers/authentication.controller.ts
src/services/authentication/auth.service.ts

fix: renamed authentication endpoint

---

src/services/filter-builder.service.ts

fix: user wallet filter

---

src/enums/visibility-type.enum.ts
src/interceptors/authorize.interceptor.ts
src/models/experience.model.ts
src/models/post.model.ts
src/services/filter-builder.service.ts
src/services/post.service.ts
src/services/user-experience.service.ts

- https://blocksphere2020.atlassian.net/browse/MYR-2749
- https://blocksphere2020.atlassian.net/browse/MYR-2750

feat: selected user visibility on post and experience

---

src/services/authentication/auth.service.ts

fix: login by wallet

---

src/__tests__/acceptance/user-social-media.acceptance.ts
src/__tests__/helpers/database.helper.ts
src/__tests__/helpers/given-instances.ts
src/__tests__/helpers/given-repositories.ts
src/controllers/user/social-media.controller.ts
src/models/identity.model.ts
src/models/index.ts
src/repositories/identity.repository.ts
src/repositories/index.ts
src/services/authentication/jwt.auth.strategy.ts
src/services/social-media/social-media.service.ts
src/services/user-otp.service.ts
src/services/user-social-media.service.ts
src/services/user.service.ts

https://blocksphere2020.atlassian.net/browse/MYR-2778

feat: endpoint to get random code for user social media

---

src/__tests__/acceptance/transaction.acceptance.ts
src/__tests__/acceptance/unlockable-content.acceptance.ts
src/__tests__/helpers/database.helper.ts
src/__tests__/helpers/given-instances.ts
src/__tests__/helpers/given-repositories.ts
src/controllers/user/index.ts
src/controllers/user/unlockable-content.controller.ts
src/enums/activity-log-type.enum.ts
src/enums/controller-type.enum.ts
src/enums/notification-type.enum.ts
src/enums/reference-type.enum.ts
src/interceptors/authorize.interceptor.ts
src/interceptors/pagination.interceptor.ts
src/models/imported-post.model.ts
src/models/index.ts
src/models/post.model.ts
src/models/unlockable-content.model.ts
src/repositories/index.ts
src/repositories/unlockable-content.repository.ts
src/services/filter-builder.service.ts
src/services/friend.service.ts
src/services/metric.service.ts
src/services/network.service.ts
src/services/notification.service.ts
src/services/post.service.ts
src/services/transaction.service.ts
src/services/user-social-media.service.ts
src/services/user.service.ts
src/services/wallet-address.service.ts
src/utils/formatter.ts

- https://blocksphere2020.atlassian.net/browse/MYR-2751

feat: unlockable content

---

src/interceptors/find-by-id.interceptor.ts
src/interceptors/pagination.interceptor.ts
src/models/friend.model.ts
src/models/post.model.ts
src/models/user-social-media.model.ts
src/models/user.model.ts
src/services/friend.service.ts
src/services/network.service.ts
src/services/post.service.ts
src/services/transaction.service.ts

fix: handle additional props in response

---

package.json

chore: bump version to 2.2.3

---

src/__tests__/acceptance/unlockable-content.acceptance.ts
src/__tests__/helpers/database.helper.ts
src/__tests__/helpers/given-instances.ts
src/__tests__/helpers/given-repositories.ts
src/controllers/user/unlockable-content.controller.ts
src/models/content-price.model.ts
src/models/index.ts
src/models/unlockable-content.model.ts
src/repositories/content-price.repository.ts
src/repositories/index.ts
src/repositories/unlockable-content.repository.ts
src/services/filter-builder.service.ts
src/services/network.service.ts
src/services/transaction.service.ts
src/services/user.service.ts
src/services/wallet-address.service.ts

https://blocksphere2020.atlassian.net/browse/MYR-2793

fix: transaction validation for content paid

---

src/services/network.service.ts
src/services/transaction.service.ts

https://blocksphere2020.atlassian.net/browse/MYR-2793

fix: rename method name when validate transaction

---

src/__tests__/acceptance/authentication.acceptance.ts
src/__tests__/acceptance/user-wallet.acceptance.ts
src/__tests__/helpers/given-instances.ts
src/models/wallet.model.ts
src/services/authentication/auth.service.ts
src/services/user.service.ts

https://blocksphere2020.atlassian.net/browse/MYR-2796

fix: authentication with email when wallet is existed

---

src/__tests__/acceptance/transaction.acceptance.ts
src/interceptors/authorize.interceptor.ts
src/models/transaction.model.ts
src/services/post.service.ts
src/services/transaction.service.ts

- https://blocksphere2020.atlassian.net/browse/MYR-2801

fix: handle transaction with alphanumeric near token

---

src/services/transaction.service.ts

https://blocksphere2020.atlassian.net/browse/MYR-2801

fix: deactivate hash validation for near

---

src/services/transaction.service.ts

fix: deactivate hash validation

---

src/services/filter-builder.service.ts

fix: fixed user filter

---

src/controllers/user/user.controller.ts
src/services/user.service.ts

https://blocksphere2020.atlassian.net/browse/MYR-2809

fix: update endpoint to get user by username

---

src/interceptors/pagination.interceptor.ts
src/services/filter-builder.service.ts

https://blocksphere2020.atlassian.net/browse/MYR-2805

fix: handle experience post when selected user only

---

src/services/filter-builder.service.ts

https://blocksphere2020.atlassian.net/browse/MYR-2811

fix: typo query friend filter

---

src/services/filter-builder.service.ts

https://blocksphere2020.atlassian.net/browse/MYR-2805

fix: query selected user in timeline

---

src/controllers/user/comment.controller.ts
src/interfaces/asset.interface.ts
src/models/comment.model.ts
src/services/comment.service.ts
src/services/social-media/social-media.service.ts
src/services/user.service.ts

https://blocksphere2020.atlassian.net/browse/MYR-2814

feat: added endpoint to count total comment

---

src/__tests__/helpers/database.helper.ts
src/controllers/user/transaction.controller.ts
src/models/currency.model.ts
src/services/filter-builder.service.ts
src/services/transaction.service.ts
src/services/user.service.ts

https://blocksphere2020.atlassian.net/browse/MYR-2815

feat: added new endpoint to get total tips received

---

src/interceptors/pagination.interceptor.ts
src/models/imported-post.model.ts
src/services/filter-builder.service.ts
src/services/post.service.ts
src/services/social-media/social-media.service.ts
src/utils/url-utils.ts

https://blocksphere2020.atlassian.net/browse/MYR-2798

fix: added query in comment collection

---

src/services/notification.service.ts
src/services/transaction.service.ts

https://blocksphere2020.atlassian.net/browse/MYR-2816

fix: improved notification for unlockable content

---

src/controllers/user/unlockable-content.controller.ts
src/interceptors/pagination.interceptor.ts
src/services/comment.service.ts
src/services/post.service.ts
src/services/user.service.ts
src/services/wallet-address.service.ts

https://blocksphere2020.atlassian.net/browse/MYR-2817

fix: added new endpoint to remove unlockable content

---

src/__tests__/acceptance/experience.acceptance.ts
src/controllers/experience/experience.controller.ts
src/services/filter-builder.service.ts

https://blocksphere2020.atlassian.net/browse/MYR-2818

fix: improved experience query

---

src/interceptors/pagination.interceptor.ts

fix: hide field content when not paid

---

src/interceptors/pagination.interceptor.ts
src/models/content-price.model.ts

https://blocksphere2020.atlassian.net/browse/MYR-2798

fix: improved get username and category

---

src/services/notification.service.ts

fix: added new field in notification addtional reference id

---

src/services/experience.service.ts
src/services/filter-builder.service.ts
src/services/user-experience.service.ts

https://blocksphere2020.atlassian.net/browse/MYR-2849
[MYR-2849]: https://blocksphere2020.atlassian.net/browse/MYR-2849?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: handle experience visibility in timeline

---

src/services/filter-builder.service.ts

https://blocksphere2020.atlassian.net/browse/MYR-2851
[MYR-2851]: https://blocksphere2020.atlassian.net/browse/MYR-2851?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: handle search experience

---

src/services/user.service.ts

https://blocksphere2020.atlassian.net/browse/MYR-2861

fix: changed action count for web2 user

---

src/__tests__/acceptance/comment.acceptance.ts
src/__tests__/acceptance/post.acceptance.ts
src/services/user-experience.service.ts
src/services/user.service.ts

fix: patch user experience

---

package.json

chore: bump version to 2.2.5
N/A

chore: bump version to 2.2.5

---

src/services/filter-builder.service.ts

https://blocksphere2020.atlassian.net/browse/MYR-2848

fix: experience post query

---

src/application.ts
src/services/authentication/auth.service.ts

fix: handle email user case insensitive

---

src/__tests__/acceptance/friend.acceptance.ts
src/services/user.service.ts
src/services/wallet-address.service.ts

https://blocksphere2020.atlassian.net/browse/MYR-2868

fix: disable friend restriction for web2 user

---

src/services/notification.service.ts

fix: notification for comment exclusive content

---

src/services/authentication/auth.service.ts

https://blocksphere2020.atlassian.net/browse/MYR-2864

fix: set email as lowercase

---

src/services/user.service.ts

https://blocksphere2020.atlassian.net/browse/MYR-2864

fix: handle checking email validation

---

src/interceptors/pagination.interceptor.ts

fix: exclusive info on comment

---

package.json

chore: bump version to 2.2.6

---

src/application.ts

fix: added new migration to remove DEIP token

---

src/services/network.service.ts

fix: error handling more descriptive on claim reference

---

package.json

chore: bump version to 2.2.7

---

src/services/network.service.ts
src/services/transaction.service.ts

https://blocksphere2020.atlassian.net/browse/MYR-2880

fix: update event data when transaction created

---

src/services/wallet-address.service.ts

https://blocksphere2020.atlassian.net/browse/MYR-2879

fix: handle claim reference of unlockable content

---

src/__tests__/acceptance/user-social-media.acceptance.ts
src/interceptors/authorize.interceptor.ts
src/services/user.service.ts

https://blocksphere2020.atlassian.net/browse/MYR-2909

fix: fixed failed to verify social media

---

package.json

chore: bump version to 2.2.8

---

seed-data/server.json
src/__tests__/acceptance/unlockable-content.acceptance.ts
src/__tests__/helpers/given-instances.ts
src/application.ts
src/models/server.model.ts
src/services/wallet-address.service.ts

fix: include instance id on server seed data

---

.maintain/deployment/GUIDE.md
.maintain/deployment/init-webserver.sh

chore: deployment guide

---

.maintain/deployment/init-webserver.sh

chore: init webserver

---

.maintain/deployment/GUIDE.md
.maintain/deployment/init-webserver.sh
.maintain/deployment/nginx.conf

chore: fix deployment

---

src/services/experience.service.ts

https://blocksphere2020.atlassian.net/browse/MYR-2925

fix: update post created at when add post to experience

---

src/services/statistic.service.ts

https://blocksphere2020.atlassian.net/browse/MYR-2916

fix: fixed average calculation

---

src/services/experience.service.ts
src/services/post.service.ts

https://blocksphere2020.atlassian.net/browse/MYR-2925

fix: handle added post to timeline

---

src/interceptors/pagination.interceptor.ts

fix: included total amount on exlusive content

---

src/services/wallet-address.service.ts

https://blocksphere2020.atlassian.net/browse/MYR-2881

fix: update reference id when fetch wallet address

---

src/services/network.service.ts
src/services/post.service.ts
src/services/wallet-address.service.ts

https://blocksphere2020.atlassian.net/browse/MYR-2918
https://blocksphere2020.atlassian.net/browse/MYR-2934
https://blocksphere2020.atlassian.net/browse/MYR-2936

fix: handle claim reference of a big number

---

src/controllers/authentication.controller.ts
src/interfaces/token.inteface.ts
src/services/authentication/auth.service.ts

fix: improve auth response when login

---

src/models/imported-post.model.ts
src/models/post.model.ts
src/services/filter-builder.service.ts

https://blocksphere2020.atlassian.net/browse/MYR-2925

fix: update order filter

---

src/services/filter-builder.service.ts

fix: update order filter on post

---

src/enums/visibility-type.enum.ts
src/models/post.model.ts
src/services/post.service.ts

- update enum visibility post
- add field selectedTimelineIds for body request
- set selectedUserIds from user ids from every timeline
- https://blocksphere2020.atlassian.net/browse/MYR-2943

feat: post timeline visibility

---

src/services/post.service.ts

- visibility post timeline
- https://blocksphere2020.atlassian.net/browse/MYR-2943

fix: visibility timeline

---

src/models/post.model.ts
src/services/post.service.ts

- save selectedTimelineIds
- find userid from timeline id

fix: selected post by timeline id

---

src/__tests__/acceptance/post.acceptance.ts
src/models/experience.model.ts
src/services/filter-builder.service.ts
src/services/post.service.ts
src/services/user-experience.service.ts

https://blocksphere2020.atlassian.net/browse/MYR-2946
https://blocksphere2020.atlassian.net/browse/MYR-2947

fix: handle filter post query

---

src/services/filter-builder.service.ts

fix: improved post filter query

---

package.json

chore: dump to 2.2.8

---

.dockerignore

ci: ignore CHANGELOG.md from docker

ci: ignore CHANGELOG.md from docker

---

.github/workflows/cicd.yaml

ci: remove GKE use internal IP

ci: remove GKE use internal IP

---

.github/workflows/cicd.yaml

ci: use GKE internal IP

---

.github/workflows/cicd.yaml

ci: change ingress tls secret name

ci: change ingress tls secret name

---

src/config.ts

fix: invalid environment name
https://blocksphere2020.atlassian.net/browse/MYR-2957

fix: invalid environment name

---

src/__tests__/acceptance/post.acceptance.ts
src/services/user.service.ts

https://blocksphere2020.atlassian.net/browse/MYR-2974

fix: remove create post limitaion

---

package.json
src/__tests__/acceptance/user-experience.acceptance.ts
src/services/user-experience.service.ts
yarn.lock

https://blocksphere2020.atlassian.net/browse/MYR-2974

fix: remove create timeline limitation

---

src/services/network.service.ts

https://blocksphere2020.atlassian.net/browse/MYR-2964

fix: handle claim reference on debio network

---

src/services/network.service.ts

https://blocksphere2020.atlassian.net/browse/MYR-2964

fix: handle claim reference with debio

---

src/services/network.service.ts

https://blocksphere2020.atlassian.net/browse/MYR-2964

fix: handle error txFeeInsufficient when claim debio

---

src/services/filter-builder.service.ts

https://blocksphere2020.atlassian.net/browse/MYR-3011

fix: include @ and # on filter post

---

src/controllers/experience/experience.controller.ts
src/services/experience.service.ts

feat: advanced search

---

src/__tests__/helpers/database.helper.ts
src/application.ts
src/interceptors/pagination.interceptor.ts
src/models/experience-post.model.ts
src/models/experience.model.ts
src/models/index.ts
src/models/timeline-config.model.ts
src/models/user-experience.model.ts
src/repositories/index.ts
src/repositories/timeline-config.repository.ts
src/services/experience.service.ts
src/services/filter-builder.service.ts
src/services/post.service.ts
src/services/user-experience.service.ts

https://blocksphere2020.atlassian.net/browse/MYR-2958

feat: update timeline query

---

src/application.ts
src/controllers/experience/experience.controller.ts
src/controllers/video-upload.controller.ts
src/enums/controller-type.enum.ts
src/interceptors/authorize.interceptor.ts
src/services/storage.service.ts
src/services/video-upload.service.ts
src/utils/upload.ts

- video upload
- advance search
- https://blocksphere2020.atlassian.net/browse/MYR-3013

fix: advance search

---

src/__tests__/helpers/database.helper.ts
src/enums/notification-type.enum.ts
src/services/notification.service.ts
src/services/vote.service.ts

Add notification service function to send notification when post or comment gained upvotes
MYR-3014

fix: upvote notification

---

src/services/experience.service.ts

https://blocksphere2020.atlassian.net/browse/MYR-3031

fix: bug fix error add post to timeline

---

src/controllers/experience/experience.controller.ts
src/services/experience.service.ts

- remove filter object
- manual param
- manual query

fix: change advanced search

---

src/application.ts
src/services/user-experience.service.ts

https://blocksphere2020.atlassian.net/browse/MYR-3032

fix: create migration

---

src/enums/notification-type.enum.ts
src/services/notification.service.ts

Patch Follower Notif Type
MYR-3015

fix: follower notif count

---

src/controllers/experience/experience.controller.ts
src/services/experience.service.ts

fix: pagination advanced search

---

src/services/filter-builder.service.ts

fix: timeline filter for single experience

---

src/services/filter-builder.service.ts

- read query created by to search experience by createdBy

fix: find by createdby

---

src/__tests__/helpers/database.helper.ts
src/controllers/experience/post.controller.ts
src/enums/user-experience-status.enum.ts
src/models/user-experience.model.ts
src/services/experience.service.ts

- update user experience subscribe when new post to timeline
- get count new post by experience id
- update user experience model, add status
- https://blocksphere2020.atlassian.net/browse/MYR-2992

fix: expirience

---

src/__tests__/helpers/database.helper.ts
src/services/post.service.ts

fix: handle empty selectedTimelineIds when creating post

---

src/__tests__/helpers/database.helper.ts
src/services/filter-builder.service.ts
src/services/post.service.ts

https://blocksphere2020.atlassian.net/browse/MYR-3039

fix: experience timeline

---

src/services/filter-builder.service.ts

https://blocksphere2020.atlassian.net/browse/MYR-3038

fix: timeline filter

---

src/services/experience.service.ts
src/services/filter-builder.service.ts

fix: date format when update user experience

---

src/application.ts
src/models/timeline-config.model.ts
src/services/filter-builder.service.ts

fix: improve timeline query

---

src/controllers/experience/post.controller.ts
src/services/experience.service.ts
src/services/filter-builder.service.ts
src/services/video-upload.service.ts

- adjustment advance search function
- adjustment video upload
- adjustment add post to timeline

refactor: api video, advanced experience

---

src/__tests__/acceptance/vote.acceptance.ts

Add:AcceptanceTest

---

src/services/filter-builder.service.ts
src/services/post.service.ts

https://blocksphere2020.atlassian.net/browse/MYR-3037

fix: resolve filter query on search timeiline

---

src/services/post.service.ts

https://blocksphere2020.atlassian.net/browse/MYR-3016
https://blocksphere2020.atlassian.net/browse/MYR-3017

fix: resolve create post

---

src/jobs/update-trending-topic.job.ts

Make trending tag cron job to be updated weekly
MYR-3053
https://blocksphere2020.atlassian.net/browse/MYR-3053?atlOrigin=eyJpIjoiNDdiNzlhZDdiZGQyNGJiNTgxMTlkNGUyMTMzODFkN2IiLCJwIjoiaiJ9

fix: weekly trending tags

---

src/__tests__/integration/services/reddit.service.integration.ts
src/datasources/reddit.datasource.ts

- fix reddit service added user agent
- N/A

fix: reddit service added user agent

---

src/__tests__/helpers/given-instances.ts

test: fix reddit url

---

src/__tests__/acceptance/user-experience.acceptance.ts
src/__tests__/acceptance/vote.acceptance.ts
src/interceptors/authorize.interceptor.ts
src/jobs/update-trending-topic.job.ts
src/services/authentication/hash.password.service.ts
src/services/authentication/jwt.auth.strategy.ts

chore: cleanup logger

---

src/datasources/twitter.datasource.ts

- fix twitter v2 base url
- N/A

fix: twitter v2 base url

---

src/datasources/twitter.datasource.ts

Reverts myriadsocial/myriad-api#886

Revert "fix: twitter v2 base url"

---

src/services/post.service.ts
src/services/user.service.ts

fix: profile

---

src/models/user.model.ts

- fix mongo index user email
- N/A

fix: mongo index user email

---

src/controllers/user/post.controller.ts

Add additional filter to make sure email is not included.

fix: remove email from get post request

---

src/controllers/user/post.controller.ts
src/controllers/user/user.controller.ts

fix: email showing on api request

---

src/__tests__/acceptance/comment.acceptance.ts
src/services/user.service.ts

Change rate limit number and include connected social media

fix: rate limit

---

.github/workflows/cicd.yaml
src/controllers/authentication.controller.ts
src/controllers/user/personal-access-token.controller.ts
src/models/index.ts
src/models/request-login-by-pat.model.ts
src/services/authentication/auth.service.ts
src/services/user.service.ts

feat: add authentication with personal access token

---

src/__tests__/helpers/database.helper.ts
src/controllers/user/experience.controller.ts
src/models/experience-editor.model.ts
src/models/experience.model.ts
src/models/index.ts
src/repositories/experience-editor.repository.ts
src/repositories/experience.repository.ts
src/repositories/index.ts
src/services/user-experience.service.ts
src/services/user.service.ts

feat: enable editors in timeline for multi user timeline

---

src/__tests__/helpers/database.helper.ts
src/controllers/user/experience.controller.ts
src/services/post.service.ts
src/services/user-experience.service.ts
src/services/user.service.ts

fix: CRUD operation involving multi user timeline editors

---

src/controllers/user/post.controller.ts
src/services/post.service.ts

fix: email leak on find post by id api

---

src/services/post.service.ts

fix: issue with private timeline

---

src/services/post.service.ts

fix: error on creating multi user timeline

---

src/services/post.service.ts

fix: issue with uploading image

---

src/services/post.service.ts

fix:embedded url

---

src/services/user.service.ts

fix: get posts by profile

---

src/enums/method-type.enum.ts
src/interceptors/pagination.interceptor.ts

fixed get posts by profile endpoint

---

src/models/experience.model.ts

feat: add exclusiveness to timeline model

---

src/services/experience.service.ts

fix: return empty array when timeline is exclusive

---

src/services/experience.service.ts

fix: update exclusive timeline exclusion logic to fetch transaction

---

src/__tests__/helpers/database.helper.ts
src/services/experience.service.ts

fix: patch database helper error

---

src/services/experience.service.ts

fix: update transaction search for exclusive timeline
